### ISSUE TITLE
DynamoDB: EventsContext fails to read when tip not read

### ISSUE THREAD

**Issue by epNickColeman** [jet/equinox#376]
The DynamoStore EventsContext fails to read events when the tip document is not included in any of the batches read.

Example stack trace:
```
 EqxDynamo QueryF ModuleSummary-caded21863a142a9bead26c92ed437d3 v977 397.6ms 95RU 32e/1 9805b >945 <null 
{
    "batchSize": 32
}

W DynamoStoreSource read failure 
{}

System.AggregateException: One or more errors occurred. (unexpected)
---> System.Exception: unexpected
at Equinox.DynamoStore.Core.Query.toPosition(LoadRes _arg1) in /_//src/Equinox.DynamoStore/DynamoStore.fs:line 850
at Equinox.DynamoStore.Core.Query.load@859.MoveNext() in /_//src/Equinox.DynamoStore/DynamoStore.fs:line 882
at <StartupCode$Equinox-DynamoStore>.$DynamoStore.Read@1072.MoveNext()
at <StartupCode$Equinox-DynamoStore>.$DynamoStore.GetInternal@1437.MoveNext() in /_//src/Equinox.DynamoStore/DynamoStore.fs:line 1448
at <StartupCode$Equinox-DynamoStore>.$DynamoStore.clo@1422-3.MoveNext() in /_//src/Equinox.DynamoStore/DynamoStore.fs:line 1423
at Propulsion.DynamoStore.Impl.materializeSpans@71-1.MoveNext() in /_//src/Propulsion.DynamoStore/DynamoStoreSource.fs:line 79
at Propulsion.DynamoStore.Impl.materializeIndexEpochAsBatchesOfStreamEvents@46.MoveNext() in /_//src/Propulsion.DynamoStore/DynamoStoreSource.fs:line 111
at FSharp.Control.TaskSeq`2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of inner exception stack trace ---
at <StartupCode$Propulsion-Feed>.$FeedSource.clo@268-60.MoveNext() in /_//src/Propulsion.Feed/FeedSource.fs:line 272
I EqxDynamo Tip 200 $AppendsEpoch-0_1 v2534 259.9ms 6RU a8c38e9cb8aa4a06b225dd08704aaada 129e 0u 47189+0b 
{}

```

**Comment by bartelink** [comment]
Resolved by #377 (which indicates the package version)
