### ISSUE TITLE
eqx stats cosmos: Handle empty container

### ISSUE THREAD

**Issue by bartelink** [jet/equinox#464]
4.1.0-alpha releases fail with an exception when `dotnet tool run eqx -Q stats cosmos -c <name of empty container>` is run on an empty container
(computation of `Oldest` does not cater for an empty resultset)

```
System.ArgumentException: The input task sequence was empty. (Parameter 'source')
   at <StartupCode$FSharp-Control-TaskSeq>.$TaskSeq.head@283.Invoke(Unit unitVar0)
   at <StartupCode$FSharp-Control-TaskSeq>.$TaskSeq.head@283-2.MoveNext()
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 453
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1133
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1160
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1504
   at Equinox.Tool.Program.main(String[] argv) in /_//tools/Equinox.Tool/Program.fs:line 840
 ```

**Comment by bartelink** [comment]
Fixed in cosmos-linq branch via using tryHead
